#This makefile is auto generated by _make.exe.
#Software info :
#  Author : Yanglin Zhang
#  Email : zhang06851@gtiit.edu.cn
#  Version : 210707.1
#Warning: Only use in GT_MCS SERVER.
#		(C) All Right Reserved
#Do not change the file unless you know what you are doing.

#Macro
CC = gcc
EXEC = operate.exe
OBJS = GSet.c Line.c operate.c Station.c System.c
COM_FLAG = -std=c99 -Wall -Werror -pedantic-errors
DEBUG_FLAG = #TO BE COMPLETE

#LINK COMMAND
$(EXEC):$(OBJS)
	$(CC) $(COM_FLAG) $(DEBUG_FLAG) -o$@ $(OBJS)

#COMPILE COMMAND

GSet.o: GSet.c GSet.h
  	$(CC) $(COM_FLAG) -c $*.c
Line.o: Line.c Line.h
	$(CC) $(COM_FLAG) -c $*.c
operate.o: operate.c System.h Station.h Line.h
	$(CC) $(COM_FLAG) -c $*.c
Station.o: Station.c Station.h
	$(CC) $(COM_FLAG) -c $*.c
System.o: System.c System.h Station.h Line.h
	$(CC) $(COM_FLAG) -c $*.c
	
GSet_test.exe:GSet_test.o GSet.o
	$(CC) $(COMP_FLAG)  GSet_test.o GSet.o -o$@ -L. -lmtm
GSet_test1.o:GSet_test1.c GSet.h
	$(CC) $(COMP_FLAG) -c $*.c
GSet_test1.exe:GSet_test1.o GSet.o
	$(CC) $(COMP_FLAG) GSet_test1.o GSet.o -o$@ -L. -lmtm
#CLEAN COMMAND
clean:
		rm -f *.o *.exe